### ISSUE TITLE
environment

### ISSUE THREAD

**Issue by duzhenjiang113** [mikacuy/joint_learning_retrieval_deformation#1]
Hi,
    It's a great job.  Could you please provide the running environmental details?

**Comment by duzhenjiang113** [comment]
It looks like the link of pre-trained model  has expired

**Comment by mikacuy** [comment]
Hi,

Thank you for your interest in our work. I have updated the pretrained models link and uploaded an environment.yml file. Let me know if these work okay for you.

Best,
Mika

**Comment by duzhenjiang113** [comment]
> Hi,
> 
> Thank you for your interest in our work. I have updated the pretrained models link and uploaded an environment.yml file. Let me know if these work okay for you.
> 
> Best,
> Mika

thanks, I'll try to run the code.

**Comment by duzhenjiang113** [comment]
Traceback (most recent call last):
  File "train_region_images.py", line 1107, in <module>
    cd_loss, _ = chamfer_distance(output_pc, x_repeat, batch_reduction=None)
  File "/home/zj/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/loss/chamfer.py", line 148, in chamfer_distance
    x_nn = knn_points(x, y, lengths1=x_lengths, lengths2=y_lengths, K=1)
  File "/home/zj/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/ops/knn.py", line 159, in knn_points
    p1_dists, p1_idx = _knn_points.apply(p1, p2, lengths1, lengths2, K, version)
  File "/home/zj/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/ops/knn.py", line 52, in forward
    idx, dists = _C.knn_points_idx(p1, p2, lengths1, lengths2, K, version)
RuntimeError: Not compiled with GPU support.

I use the environment you provided. But I meet this problem. It seems that some tool's version is not suited.  Could you please give me some advice? Thanks again.

**Comment by mikacuy** [comment]
It looks like the installation of pytorch3d is not GPU supported. It might have been installed just for CPU computation. 

Please have a look at this for a fix: https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md

It says there that if you install with pip the default build is CPU only.

**Comment by duzhenjiang113** [comment]
> It looks like the installation of pytorch3d is not GPU supported. It might have been installed just for CPU computation.
> 
> Please have a look at this for a fix: https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md
> 
> It says there that if you install with pip the default build is CPU only.

okay, it works, thanks !!!
